### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by keybits** [gethyas/doks-core#42]
## Summary

Add an RSS feed 

### Basic example

Same functionality as in the old Doks 

### Motivation

So that people can follow the blog with a feed reader.

**Comment by h-enk** [comment]
A main feed *and* section feeds are there. E.g. for the Doks v1 branch:

- https://v1--doks.netlify.app/index.xml
- https://v1--doks.netlify.app/blog/index.xml

Note, these feeds [fail validation](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fv1--doks.netlify.app%2Findex.xml) because the URL is not set properly. But when set correctly, the feed will be [valid](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fdoks.netlify.app%2Fblog%2Findex.xml).

**Comment by keybits** [comment]
Thank you! Sorry for missing that they were there. I can set the validation and link in the `head`.
